---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: khinkali/nexus:todo
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: data-dir
          mountPath: /nexus-data
      initContainers:
      - name: clone-repo
        image: alpine/git:1.0.4
        securityContext:
          runAsUser: 200
        command: ["/bin/sh", "-c", "git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.org/khinkali/nexus_backup /nexus-data"]
        volumeMounts:
        - name: data-dir
          mountPath: /nexus-data
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: password
      volumes:
      - name: data-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30181
  type: NodePort
